config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end

  root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  
  before_action :authenticate_user!
  before_action :admin_required


  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "创建成功"
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path, notice: "修改成功"
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path, alert: "删除成功"
  end

  def admin_required
    if !current_user.admin?
      redirect_to "/"
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "成功将#{@product.title}加入购物车"
    else
      flash[:warning] = "你的购物车内已有此物品"
    end
    #redirect_to :back
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<!-- <div class="col-md-4 col-md-offset-4"> -->
  <h2>修改商品</h2>
  <hr>

<%= simple_form_for [:admin, @product]  do |p| %>

  <!-- 商品名称： -->
  <div class="group">
    <%= p.input :title %>
    <!-- <%= p.text_field :title %> -->
  </div>


  <!-- 描述: -->
  <div class="group">
    <%= p.input :description %>
    <!-- <%= p.text_area :description %> -->
  </div>


  <!-- 价格： -->
  <div class="group">
    <%= p.input :price %>
    <!-- <%= p.text_field :price %> -->
  </div>


  <!-- 数量 -->
  <div class="group">
    <%= p.input :quantity %>
    <!-- <%= p.text_field :quantity%> -->
  </div>


  <!-- 图片如果显示 -->
  <% if @product.image.present? %>
    <span>目前商品图</span> <br>
    <%= image_tag(@product.image.thumb.url) %>
  <% end %>

  
  <div class="group">
    <%= p.input :image, as: :file %>
  </div>

  <br>

  <%= p.submit "Submit", :disable_with => 'submiting...' %>
<% end %>
<!-- </div> -->

app/views/admin/products/index.html.erb
<h2>Product List</h2>

<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("add product", new_admin_product_path, class: "btn btn-primary btn-sm")%>
</div>

<table class="table table-boldered">
  <thead>
    <tr>
      <th>#</th>
      <th width='220'>图片</th>
      <th>品名</th>
      <th>价格</th>
      <th >选项</th>
      <th>创建时间</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.image.present? %>
              <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td>
          <%= link_to("edit", edit_admin_product_path(product),  class: "btn btn-primary") %>|
          <%= link_to("delete", admin_product_path(product), :method => :delete, class: "btn btn-primary") %>
        </td>
        <td>
          <%= product.created_at %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- <ul>
  <%= @products.each do |product| %>
    <li><%= link_to(product.title, admin_product_path(product)) %></li>
  <% end %>
</ul> -->

app/views/admin/products/new.html.erb
<!-- <div class="col-md-4 col-md-offset-4"> -->
  <h2>新增商品</h2>
  <hr>

<%= simple_form_for [:admin, @product]  do |p| %>

  <!-- 商品名称： -->
  <div class="group">
    <%= p.input :title %>
    <!-- <%= p.text_field :title %> -->
  </div>


  <!-- 描述: -->
  <div class="group">
    <%= p.input :description %>
    <!-- <%= p.text_area :description %> -->
  </div>


  <!-- 价格： -->
  <div class="group">
    <%= p.input :price %>
    <!-- <%= p.text_field :price %> -->
  </div>


  <!-- 数量 -->
  <div class="group">
    <%= p.input :quantity %>
    <!-- <%= p.text_field :quantity%> -->
  </div>



  <!-- 上传图片 -->
  <!-- 图片 -->
  <%#= p.text_file :image%>
  <div class="group">
    <!-- <%= p.file_field :image, accept: 'image/png,image/jpeg'%> -->
    <%= p.input :image, as: :file %>
  </div>

  <br>

  <%= p.submit "Submit", :disable_with => 'submiting...' %>
<% end %>
<!-- </div> -->